/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.EmpleadoController;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Empleado;
import models.EmpleadoPermanente;
import models.EmpleadoTemporal;

/**
 *
 * @author ljgarciao
 */
public class GestionEmpleados extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionEmpleados.class.getName());

    /**
     * Creates new form GestionEmpleado
    */    
    private EmpleadoController control = new EmpleadoController();
    public GestionEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void cargarTabla(){
        DefaultTableModel modelo = (DefaultTableModel)tablaEmpleados.getModel();
        modelo.setRowCount(0); //Limpiar tabla
        
        for(Empleado p:control.listarEmpleado()){
            String tipo = "";
            String infExtra = "";
            if(p instanceof EmpleadoPermanente){ //En caso que tenga el extend de empleado permanente
                tipo = "Permanente";
                EmpleadoPermanente emp = (EmpleadoPermanente) p;
                infExtra = "Bono: " + emp.getBonoAntiguedad() + ". Beneficios: " + emp.getBeneficios() + ".";
            }else{
                tipo = "Temporal";
                EmpleadoTemporal emp = (EmpleadoTemporal) p;
                infExtra = "Fin contrato: " + emp.getFechaContrato();
            }
            Object[] fila={
                p.getIdEmpleado(),
                p.getNombre(),
                p.getFechaingreso(),
                tipo,
                infExtra
            };
            modelo.addRow(fila);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        btnAgregarEmpleado = new javax.swing.JButton();
        bntModificarEmpleado = new javax.swing.JButton();
        bntBuscarEmpleado = new javax.swing.JButton();
        bntEliminarEmpleado = new javax.swing.JButton();
        btnVolverProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 28, 51));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de empleados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(43, 129, 140));

        jScrollPane1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        tablaEmpleados.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Fec ingreso", "Tipo empleado", "Información adicional"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEmpleados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaEmpleados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaEmpleados);
        if (tablaEmpleados.getColumnModel().getColumnCount() > 0) {
            tablaEmpleados.getColumnModel().getColumn(0).setResizable(false);
            tablaEmpleados.getColumnModel().getColumn(0).setPreferredWidth(50);
            tablaEmpleados.getColumnModel().getColumn(1).setResizable(false);
            tablaEmpleados.getColumnModel().getColumn(2).setResizable(false);
            tablaEmpleados.getColumnModel().getColumn(2).setPreferredWidth(70);
            tablaEmpleados.getColumnModel().getColumn(3).setResizable(false);
            tablaEmpleados.getColumnModel().getColumn(3).setPreferredWidth(70);
            tablaEmpleados.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        btnAgregarEmpleado.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnAgregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar.png"))); // NOI18N
        btnAgregarEmpleado.setText("Agregar");
        btnAgregarEmpleado.addActionListener(this::btnAgregarEmpleadoActionPerformed);

        bntModificarEmpleado.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bntModificarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modificar.png"))); // NOI18N
        bntModificarEmpleado.setText("Modificar");
        bntModificarEmpleado.addActionListener(this::bntModificarEmpleadoActionPerformed);

        bntBuscarEmpleado.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bntBuscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        bntBuscarEmpleado.setText("Buscar");
        bntBuscarEmpleado.addActionListener(this::bntBuscarEmpleadoActionPerformed);

        bntEliminarEmpleado.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        bntEliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminar.png"))); // NOI18N
        bntEliminarEmpleado.setText("Eliminar");
        bntEliminarEmpleado.addActionListener(this::bntEliminarEmpleadoActionPerformed);

        btnVolverProducto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnVolverProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/volver.png"))); // NOI18N
        btnVolverProducto.setText("Volver");
        btnVolverProducto.addActionListener(this::btnVolverProductoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bntEliminarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntBuscarEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntModificarEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAgregarEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntModificarEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntBuscarEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntEliminarEmpleado)
                        .addGap(92, 92, 92)
                        .addComponent(btnVolverProducto))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModificarEmpleadoActionPerformed
        PantallaPrincipal ventana = new PantallaPrincipal();
        ModificarEmpleados empleados = new ModificarEmpleados(ventana,true,this.control);
        empleados.setLocationRelativeTo(null);
        empleados.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_bntModificarEmpleadoActionPerformed

    private void bntBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarEmpleadoActionPerformed
        PantallaPrincipal ventana = new PantallaPrincipal();
        BuscarEmpleados empleados = new BuscarEmpleados(ventana,true,this.control);
        empleados.setLocationRelativeTo(null);
        empleados.setVisible(true);
    }//GEN-LAST:event_bntBuscarEmpleadoActionPerformed
    
    private void btnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoActionPerformed
        PantallaPrincipal ventana = new PantallaPrincipal();
        CrearEmpleados empleados = new CrearEmpleados(ventana,true);
        empleados.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_btnAgregarEmpleadoActionPerformed

    private void btnVolverProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverProductoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverProductoActionPerformed

    private void bntEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEliminarEmpleadoActionPerformed
        int fila = tablaEmpleados.getSelectedRow();
        if(fila==-1)
            JOptionPane.showMessageDialog(this,"Seleccione un empleado de la tabla");
        else{
            String Emp=tablaEmpleados.getValueAt(fila,1).toString(); //Selecciona fila
            int confirm = JOptionPane.showConfirmDialog(this,"Desea eliminar el empleado " + Emp + "?","Confirmar eliminación",JOptionPane.YES_NO_OPTION,JOptionPane.ERROR_MESSAGE);
            if(confirm == JOptionPane.YES_OPTION){
                boolean borrar = control.eliminarEmpleado(Emp);
                if(borrar){
                    JOptionPane.showMessageDialog(this,"Empleado eliminado");
                    cargarTabla();
                }else{
                    JOptionPane.showMessageDialog(this,"Error: no se pudo eliminar el empleado");
                }                
            }
        }
    }//GEN-LAST:event_bntEliminarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscarEmpleado;
    private javax.swing.JButton bntEliminarEmpleado;
    private javax.swing.JButton bntModificarEmpleado;
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnVolverProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables
}